version: "2.0"
services:
  jenkins:
    image: jenkins
    user: "20000:20000"
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - /srv/dockercontainer/jenkins_home:/var/jenkins_home




































